[env]
SUPABASE_URL = "https://miracosta-vacancy.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wcXF6ZGRld2N5enVnYmJncnJ3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzY0OTg2MSwiZXhwIjoyMDc5MjI1ODYxfQ.D12ecLbpCgpXHI7OLtlyoBDPuPK5UOoLsYGeFeXcGTA"
RAKUTEN_APP_ID = "1030644021652765205"
APP_URL = "http://localhost:3004"
